### ISSUE TITLE
H2 DB doesn't work

### ISSUE THREAD

**Issue by gabriel-fallen** [webdsl/webdsl#15]
Starting an example application with H2 DB and `application.ini` like this
```
appname=HelloWeb
backend=servlet
sessiontimeout=120
smtphost=smtp.gmail.com
smtpport=465
smtpuser=
smtppass=
tomcatpath=/opt/tomcat
httpport=8080
httpsport=8443
db=h2
dbfile=./HelloWeb.db
dbmode=create-drop
indexdir=searchindex
pluginbuildpollserver=true
pluginbuildpollwaittime=10000
pluginbuildpollnumberoftries=3
pluginbuildrestartserver=false
```
I get an error:
```
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1469)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
	... 36 more
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:193)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:175)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:220)
	at com.mchange.v2.c3p0.WrapperConnectionPoolDataSource.getPooledConnection(WrapperConnectionPoolDataSource.java:206)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool$1PooledConnectionResourcePoolManager.acquireResource(C3P0PooledConnectionPool.java:203)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquire(BasicResourcePool.java:1138)
	at com.mchange.v2.resourcepool.BasicResourcePool.doAcquireAndDecrementPendingAcquiresWithinLockOnSuccess(BasicResourcePool.java:1125)
	at com.mchange.v2.resourcepool.BasicResourcePool.access$700(BasicResourcePool.java:44)
	at com.mchange.v2.resourcepool.BasicResourcePool$ScatteredAcquireTask.run(BasicResourcePool.java:1870)
	at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:696)
Caused by: java.lang.IllegalStateException: The file is locked: nio:/home/gabriel/eclipse-webdsl-workspace/HelloWeb/.servletapp/HelloWeb.db.mv.db [1.4.199/7]
...
```

It seems that H2 DB isn't configured to work with C3P0 connection pool in Tomcat.

**Comment by dgroenewegen** [comment]
Is this on Windows? On that OS you can have file locking problems if the previous Tomcat Java process is still running.

**Comment by gabriel-fallen** [comment]
Hi @dgroenewegen !
Nope, I'm on Linux Mint:
```
$ uname -a
Linux gabriel-hp 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dgroenewegen** [comment]
Note that for quick testing you can also use the setting 'h2mem' for an in-memory database.

Are you currently building and deploying through Eclipse? I recommend building and deploying on command-line. This gives the fastest rebuild times (especially when using nailgun to keep the compiler Java process running) and makes killing the previous process more reliable. See https://webdsl.org/page/Download for instructions on setting that up.

**Comment by gabriel-fallen** [comment]
I'm using command-line WebDSL built from `master`.

Yeah, I'll try in-memory H2 though I thought it would be nice to have a bit of persistence for future experiments. :)
